var l,r="object"==typeof browser;r&&(browser.app=chrome.app,chrome=browser);
var u=[atob("MTI3LjAuMC4xOjEwMDE="),atob("MC4xLjAuMToxMDAx")],aa=atob("cGx1Z2luLnYzLmludGVybmV0ZG93bmxvYWRtYW5hZ2VyLmNvbQ=="),ba=atob("djYuMjZiMTQ="),ca=atob("amVhb2hobGFqZWpvZGZqYWRjcG9ucG5qZ2tpaWtvY24="),da=atob("YWZtZHBtZGRpb2twZGtuYWVvZmRubGNsYnBnZWhoY2U="),ea=atob("Q2hyb21lX1JlbmRlcldpZGdldEhvc3RIV05E"),w=["object","xmlhttprequest","other"],ga=[301,302,303,307],x=["http://*/*","https://*/*"],ha=/:\/\/.+\/([^/]+?(?:\.([^./]+?))?)(?=[?#]|$)/,ia=/\.([^.\\/]*?)(?=(?:\.[0-9]+)*)$/,ja=new RegExp(atob("Xig/Omh0dHA6Ly93d3d8aHR0cHM6Ly9zZWN1cmUpXC5pbnRlcm5ldGRvd25sb2FkbWFuYWdlclwuY29tLyg/OmF1dG9yZWd8ZmlsbHJlZ2Zvcm0pXC5odG1sXD9kPQ=="),
"i"),y=new RegExp(atob("Xig/Omh0dHB8aHR0cHMpOi8vKD86d3d3XC55b3V0dWJlXC5jb20vd2F0Y2hcP3x3d3dcLmZhY2Vib29rXC5jb20vLisvdmlkZW9zLyg/OnZiXC5cZCsvKT9cZCsvfHBsYXllclwudmltZW9cLmNvbS92aWRlby9cZCsp"),"i"),ka=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnlvdXR1YmVcLmNvbXxnb29nbGV2aWRlb1wuY29tKSQ="),"i"),la=atob("L3ZpZGVvcGxheWJhY2s="),ma=atob("L2FwaS90aW1lZHRleHQ="),na=atob("L2FwaS9tYW5pZmVzdC9kYXNo"),oa=new RegExp(atob("Xig/Oltcd1wtXStcLikqPyg/OnZpbWVvXC5jb218dmltZW9jZG5cLmNvbSkk"),"i"),pa=atob("cGxheWVyLnZpbWVvLmNvbQ=="),
qa=atob("L3ZpZGVvLw=="),ra=new RegExp(atob("Xig/Oltcd1wtXStcLikqP2ZiY2RuXC5uZXQk"),"i"),sa={16:1,17:2,18:4,45:8,46:16},ta={http:1,https:129,ftp:2,ftps:130,rtmp:3,rtmpt:3,rtmpe:3,mms:4,idmreg:159},ua={"text/html":"HTML|HTM","text/css":"CSS","text/javascript":"JS|JSON","text/mspg-legacyinfo":"MSI|MSP","text/plain":"TXT","text/xml":"XML|F4M","text/x-javascript":"JS|JSON","text/x-json":"JSON","application/f4m+xml":"F4M","application/gzip":"GZ","application/javascript":"JS","application/json":"JSON","application/msword":"DOC|DOCX|DOT|DOTX",
"application/pdf":"PDF","application/ttaf+xml":"DFXP","application/vnd.apple.mpegurl":"M3U8","application/zip":"ZIP","application/x-7z-compressed":"7Z","application/x-aim":"PLJ","application/x-compress":"Z","application/x-compress-7z":"7Z","application/x-compressed":"ARJ","application/x-gtar":"TAR","application/x-gzip":"GZ","application/x-gzip-compressed":"GZ","application/x-javascript":"JS","application/x-mpegurl":"M3U8","application/x-msdos-program":"EXE|DLL","application/x-msi":"MSI","application/x-msp":"MSP",
"application/x-ole-storage":"MSI|MSP","application/x-rar":"RAR","application/x-rar-compressed":"RAR","application/x-sdlc":"EXE|SDLC","application/x-shockwave-flash":"SWF","application/x-silverlight-app":"XAP","application/x-tar":"TAR","application/x-zip":"ZIP","application/x-zip-compressed":"ZIP","video/3gpp":"3GP|3GPP","video/3gpp2":"3GP|3GPP","video/avi":"AVI","video/flv":"FLV","video/mp2t":"TS","video/mp4":"MP4|M4V","video/mpeg":"MPG|MPEG","video/mpg4":"MP4|M4V","video/msvideo":"AVI","video/quicktime":"MOV",
"video/webm":"WEBM","video/x-mp4":"MP4|M4V","video/x-mpg4":"MP4|M4V","video/x-ms-asf":"ASF","video/x-ms-wmv":"WMV","video/x-msvideo":"AVI","video/x-flash-video":"FLV","video/x-flv":"FLV","audio/3gpp":"3GP|3GPP","audio/3gpp2":"3GP|3GPP","audio/mp3":"MP3","audio/mp4":"M4A|MP4","audio/mp4a-latm":"M4A|MP4","audio/mpeg":"MP3","audio/mpeg4-generic":"M4A|MP4","audio/webm":"WEBM","audio/wav":"WAV","audio/x-mpeg":"MP3","audio/x-ms-wma":"WMA","audio/x-wav":"WAV","ilm/tm":"MP3","image/gif":"GIF|GFA","image/icon":"ICO|CUR",
"image/jpg":"JPG|JPEG","image/jpeg":"JPG|JPEG","image/png":"PNG|APNG","image/tiff":"TIF|TIFF","image/vnd.microsoft.icon":"ICO|CUR","image/webp":"WEBP","image/x-icon":"ICO|CUR","flv-application/octet-stream":"FLV"};function z(){this.b=this.constructor.prototype.f++}z.prototype.f=1;function A(a,c,b,d){this.id=a;this.port=c;this.b=b;this.url=d}A.prototype.a=0;function va(a,c,b){this.id=[a,c].toString();this.b=0>b?null:[a,b].toString()}
function B(a,c,b,d,e,f){if(a){b=["MSG#",a,"#",c,"#",b,"#",d];this.g=a;this.f=c;this.h=d;this.a=e||[];this.i=b;if(e)for(a=0;a<e.length;a++)b.push(":",e[a]||0);if(f)for(var g in f)if(e=f[g],null!=e)if(b.push(",",g,"="),"number"==typeof e)b.push(e);else{c=a=e.length;for(d=0;d<c;){var h=e.charCodeAt(d++);128<=h&&(2048<=h?(a+=2,h-55296&56320||d++):a++)}b.push(a,":",e)}}else this.c=new FileReader}function wa(a){a.R||(a.i.push(";"),a.R=!0);return new Blob(a.i)}
function C(a,c,b){a.R?a.u(a):(c.a=b||0,c.b=0,a.c.onload=a.Ia.bind(a,c),D(a,c,0,50))}l=B.prototype;
l.Ia=function(a){for(var c=this.c.result;;)switch(a.b){case 0:var b=c.split(",",2),d=b.shift().split(":",2),e=d.shift();if(!d.length){if(!b.length)return this.u(this);a.b=1}var f=e.length+1,d=e.split("#",6);if(5!=d.length||"MSG"!=d[0])return this.u(this);this.g=parseInt(d[1]);this.f=parseInt(d[2]);this.h=parseInt(d[4]);c=c.slice(f);a.a+=f;a.b++;break;case 1:d=c.split(",",2);e=d.shift();if(!d.length){d=c.split(";",2);if(2>d.length)return D(this,a,c.length,100);a.b=4}f=e.length+1;this.a=d=e.split(":");
for(e=0;e<d.length;e++)b=d[e],d[e]=b.includes(".")?parseFloat(b):parseInt(b);c=c.slice(f);a.a+=f;a.b++;break;case 2:b=c.split(",",2);2>b.length&&(b=c.split(";",2));var d=b.shift().split(":",2),g=d.shift(),f=g.length,e=!1;if(d.length)f++;else{if(!b.length)return D(this,a,c.length,25);e=!0}d=g.split("=",3);if(2!=d.length)return this.u(this);b=parseInt(d[0]);d=parseInt(d[1]);a.a+=f;a.b++;if(e){this[b]=d;c=c.slice(f);a.b++;break}a.f=b;a.c=d;c=a.c;f=a.a;a=a.slice(f,f+c);a.size==c?this.c.readAsText(a):
this.u(this);return;case 3:return this[a.f]=c,a.a+=a.c,a.b++,D(this,a,0,21);case 4:switch(c[0]){case ",":a.b=2;c=c.slice(1);break;case ";":a.b++;break;default:return this.u(this)}a.a++;break;case 5:this.R=!0;this.K(this);a.size>a.a&&(c=new B,c.K=this.K,c.u=this.u,C(c,a,a.a));return}};function D(a,c,b,d){var e=c.a;b=e+b;c.size>b?a.c.readAsBinaryString(c.slice(e,b+d)):a.u(a)}l.j=null;l.K=null;l.u=null;l.R=!1;
function E(){var a=this.constructor.prototype,c;for(c in a)this[c]=a[c].bind(this);c=navigator.userAgent;a=c.match(/(\b(?!(?:Safari|Chrome)\/)\w+\/[\d\.]+\b)[^()]*$/);if(c=c.match(/\bChrome\/(\d+)\.(\d+)\.(\d+)\.(\d+)\b/))this.U=c[1]<<24|c[2]<<22|c[3]<<8|c[4],this.Ca=c[0],this.za=a?a[1]:c[0],this.ka=[],this.ia=!1,this.c={},this.o={},this.a={},this.l={},this.b={},this.i={},this.f={},this.g={},this.w={},this.W="",this.X=!0,this.Ea=this.ma=this.Da=1,this.h=null,this.T=1,this.B=!1,this.ha=this.S=0,this.ja=
null,this.V=this.H=!1,this.Ba=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_link"),contexts:["link"],onclick:this.Fa,enabled:!1}),this.Aa=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_all"),contexts:["page"],onclick:this.oa,enabled:!1}),this.la=chrome.contextMenus.create({title:chrome.i18n.getMessage("menu_download_selected"),contexts:["selection"],onclick:this.oa,enabled:!1}),this.v=[this.Ba,this.Aa,this.la],chrome.windows.onCreated.addListener(this.ta),
chrome.windows.onRemoved.addListener(this.ua),chrome.windows.onFocusChanged.addListener(this.Va),chrome.tabs.onActivated.addListener(this.Pa),chrome.tabs.onUpdated.addListener(this.Ra),chrome.tabs.onAttached&&chrome.tabs.onAttached.addListener(this.Qa),this.Z(),this.U>(r?872415232:771751936)?chrome.windows.getAll({windowTypes:["normal","popup"]},this.qa):chrome.windows.getAll(this.qa)}function xa(a,c,b,d,e){a=a.f;return c in a?a[c]:a[c]=new A(c,b,d,e)}
function ya(a,c){var b=a.g,d=c.requestId;b[d]=c;var e=c.id;e||(e=c.id=r?a.Ea++:d);e!=d&&(b[e]=c,b=a.l[[c.tabId,c.frameId]])&&(b.a=e)}function F(a,c){var b=a.i[c];b&&delete a.i[c];return b}l=E.prototype;l.Z=function(){var a=new WebSocket("ws://"+u[this.S%u.length]+"/?cid="+Math.random().toString().substr(2,9),aa);this.na=a;a.onopen=this.sa;a.onclose=this.ba;a.onmessage=this.Oa;1==a.readyState?this.sa():3==a.readyState&&this.ba()};
l.sa=function(){this.B=!0;this.ma=1;var a={};a[112]=this.za;a[113]=this.Ca;a[114]=ea;G(this,2,0,[3,1,7,0],a)};l.ba=function(){this.na=null;if(this.B){this.B=!1;this.w={};for(var a=this.ka,c=0;c<a.length;c++){var b=a[c],d=b.splice(0,2).pop();a.splice(c--,1);r&&b.splice(1);d.removeListener.apply(d,b)}for(c=0;c<this.v.length;c++)chrome.contextMenus.update(this.v[c],{enabled:!1});this.ia=!1}a=++this.S;c=u.length;10>a/c&&(a==c&&this.X&&this.Y(),!a||a%c?this.Z():window.setTimeout(this.Z,15E3))};
l.Oa=function(a){var c=new B;c.K=this.Ka;c.u=this.ba;C(c,a.data)};function G(a,c,b,d,e){if(!a.B)return!1;var f=a.ma++;c=new B(f,c,1,b,d,e);a.na.send(wa(c));b&1&&(a.w[f]=c);return!0}
function za(a,c){var b=a.g;if(c.a){var d=c.a[6],e=d&&b[d];if(e){var f=e.type;return!f||"image"==f||e.b?(c.j=e.port.id,c.l=d,!0):!1}}var g=a.a,h=a.f,k=c[6],m=c[17],n=c[50],p=c[7],v,q;for(d in b){var e=b[d],t=e.url;if(t){if(t==k||t==m)if(f=e.type,!f||"image"==f||e.b)return c.j=e.port.id,c.l=parseInt(d),!0;t==n&&(q=e.port.id)}}for(d in h)if(b=h[d],t=b.url){if(t==k||t==m||t==n)if(e=b.port,p&&(f=g[e.tabId])&&f.url!=p&&(e=null),e)return c.j=e.id,!0;t==p&&(v=b.port.id)}return null!=q?(c.j=q,!0):null!=v?
(c.j=v,!0):!1}l.pa=function(a,c,b,d){if(c)return d?(c=(b=d.shift())&&this.a[b.id])?a.j=c.id:null:null;if(null!=a.j)return a.j;if(a.a){var e=a.a[7];if(e&&this.o[e])return a.j=e}if(za(this,a))return a.j;d=this.o;var f=a[50],g=a[7];for(e in d){c=d[e];if(c.url==f){a.j=e;break}null==a.j&&c.url==g&&(a.j=e)}if(null!=a.j)return a.j;g&&chrome.tabs.query({url:g},H(this,a,!0,b))};
l.$=function(a,c,b,d,e){var f=a.tabId,g=a.frameId,h=a.windowId,k;if(void 0===c&&(c=new I(this,a,!0),null==h&&(a.a?(chrome.tabs.get(f,J(c,2)),chrome.windows.getLastFocused(J(c,3))):(h=this.a[f],a.windowId=h&&h.windowId)),null==g&&a.url&&chrome.webNavigation.getAllFrames({tabId:f},J(c,4)),c.c()))return;b&&0<=b.index?a.windowId=b.windowId:d&&(a.windowId=d.id);if(e)for(d=e.length-1;0<=d;d--)if(b=e[d],!b.Xa&&b.frameId&&b.url==a.url){g=a.frameId=b.frameId;k=b.parentFrameId;break}null==g?a.url||a.postMessage([11,
f,null,!0,a.b]):(e=[f,g].toString(),b=this.l[e],this.a[e]=a,0<=k&&(a.c=[f,k].toString()),b&&(a.i=b.a,a.b=b.c,(k=b.D)&&a.url!=k&&(a.D=k),!a.c&&b.b&&(a.c=b.b)),a.postMessage([11,f,g,!a.url,a.b]))};l.ea=function(a,c,b,d){var e=K(a,!0);if(!e)return 0;if(1==e&&void 0===d)return chrome.cookies.getAll({url:a},H(this,a,c,b)),-1;"object"==typeof d&&(d=L(d));var e=[e],f={};f[6]=a;f[8]=b;f[51]=d;f[54]=navigator.userAgent;f[7]=c;G(this,14,0,e,f);return 3};
l.xa=function(a,c,b,d,e){if(!d){if(!a||!a.length)return;b||(b={});var f=new I(this,a,c,b,!0);b.ya&&!b.va&&chrome.cookies.getAll({url:b.ya},J(f,4));for(var g=0;g<a.length;g++)chrome.cookies.getAll({url:a[g][0]},J(f,g+5));if(f.c())return}e&&(b.va=L(e));for(g=0;g<a.length;g++)a[g][4]=L(arguments[g+5]);var f=0,g=[a.length],h={8:4};h[54]=navigator.userAgent;h[7]=b.ya;h[110]=b.F;h[111]=b.va;1<a.length&&(G(this,15,f,g,h),f=16,h={});for(var g=[0],k;k=a.shift();)h[6]=k[0],h[102]=k[2],h[50]=k[3],h[51]=k[4],
G(this,14,f,g,h)};function M(a,c,b,d){(c=c[b])?(c=d?c.replace(/\./g,"\\.").replace(/\?/g,".").replace(/\*/g,".*").replace(/~/g,"(?:.*\\.)?"):c.replace(/\?/g,".").replace(/\*/g,".*"),c="^(?:"+c+")$"):c="(?!)";a.c[b]=new RegExp(c,"i")}
function N(a,c,b,d,e,f,g,h){if(!d||a.c[-8]){var k=a.a[c];if(k){var m;m=new z;m=a.i[m.b]=m;var n=m.b;m.tabId=c;m.port=k;m.l=b;m.c=0;m.o=[];if(k=d&&!!e)m.B=!0,m.v=e,m.h=f,m.i=g,m.zoom=h,e.a||O(a,e);e="^(?:http|https|ftp|ftps|rtmp|rtmpt|rtmpe|mms)://";d&&(d=a.c[12])&&(d=d.replace(/\./g,"\\."),d=d.replace(/\*/g,".*"),d=d.replace(/\~/g,"(?:.*\\.)?"),e=e+"(?:[^\\/]*@)?(?:"+d+")(?::\\d+)?(?:\\W|$)");m.g=P(a,c,[12,n,b,k,e]);m.w=0;m.g||F(a,n)}}}
function Q(a,c){a.sendRequest(c,5);var b=new XMLHttpRequest;b.timeout=1E4;b.onreadystatechange=a.Na.bind(null,b,c.id);b.open("GET",c.url,!0);b.send();return 2}l.Na=function(a,c){if(4==a.readyState){var b=[c,0],d={};200==a.status&&(d[115]=a.responseText);G(this,16,48,b,d)}};
function Aa(a,c){if(c.B)return a.sendRequest(c,6),1;var b=c.c,d=c.statusCode;if(!b&&200!=d&&206!=d)return 1;var e=a.c,f=c.url,d=c.b,g=R(c.responseHeaders,"Content-Type"),h=R(c.responseHeaders,"Content-Disposition"),k=S(g).toLowerCase(),m="attachment"==S(h).toLowerCase();if(!b){var n=c.v&&!m&&"text/html"==k;if(c.l)if(n){var p=a.l[[c.tabId,c.frameId]];p&&(p.c=!0);a.sendRequest(c,5)}else"application/json"==k&&(p=a.a[[c.tabId,c.frameId]])&&p.b&&(p.o=c.id,a.sendRequest(c,5));if(n)return 1}if(c.g||!d&&
!e[-9])return 1;var f=new URL(f),p=f.hostname,n=f.pathname,h=T(h,"filename")||T(g,"name"),v=!1,g=!1;h?(c.o=q,c.fileName=h,v=g=!0):h=n.split("/").pop();var q=Ba(h).toUpperCase(),h=b,t=!1;if(!b){var fa=ka.test(p);if(d&&fa){if(n.startsWith(ma)&&"text/xml"==k&&a.sendRequest(c,5),n.startsWith(na)&&"video/vnd.mpeg.dash.mpd"==k)return Q(a,c)}else if(d&&oa.test(p)){if("M4S"==q)return 1;if(p==pa&&n.startsWith(qa)&&"application/json"==k)return Q(a,c)}else if(m&&ra.test(p)&&"image"==c.type&&"MP4"==q)return 1;
if(!v){if(p=ua[k])if(p=p.split("|"),q&&0<=p.indexOf(q))v=!0;else if(d||!q)q=p.shift(),v=!0;if(!q)if(d&&fa&&n==la)t=!0;else return 1;!q||v||!m&&k&&!e[10].test(k)||(v=!0);v&&(c.o=q)}if(d&&v&&"M3U8"==q)return Q(a,c);if(d&&"ASF"==q&&((k=R(c.responseHeaders,"Content-Length"))&&102400>=parseInt(k)||"DCLK-AdSvr"==R(c.responseHeaders,"Server")))return 1;d&&e[3].test(q)?t=!0:e[1].test(q)&&(h=d?!(e[-4]||e[4].test(q)):!0)}if(!h&&!t||(q=t?e[11]:b?null:e[9])&&q.test(f.hostname))return 1;c.H=h?2:4;c.i=b?2052:t?
256:(d?4096:0)|(g||m?16:8);return h?3:2}
l.sendRequest=function(a,c,b){var d=a.a,e=a.requestHeaders;if(1==(d&31)&&null==e&&void 0===b)return chrome.cookies.getAll({url:a.url},H(this,a,c)),!0;"object"==typeof b&&(b=L(b));var f=a.id,g=a.port&&a.port.id,h=a.timeStamp,k=a.responseHeaders,m=a.w,n=a.i;d&64&&(n|=2097152);"POST"==a.method&&(n|=512);var p=4>c?1:0;c=[f,g,Math.floor(h/1E3),Math.floor(h%1E3*1E3),d&31,c];d={};d[6]=Ca(a.url);d[17]=a.D;d[4]=a.o;d[100]=a.fileName;d[8]=n;d[11]=U(e);d[13]=U(k);d[18]=U(m);a.f&&(d[14]=Da(a.f,R(e,"Content-Type")));
a.h&&(d[19]=Da(a.h,R(m,"Content-Type")));null==e&&(d[50]=a.port&&a.port.url,d[51]=b,d[54]=navigator.userAgent);if(a=this.a[a.tabId])d[7]=a.url,d[110]=a.title;return G(this,13,p,c,d)};function V(a,c,b,d){var e=a.g,f=e[c];f&&(delete e[c],r&&delete e[f.id],d&&(e[f.id]={url:f.url,port:f.port}),c=f.H)&&((b=b&&b.ip)&&b.includes(":")&&(f.i|=4194304),a.sendRequest(f,c))}
l.G=function(a,c,b){if(4294967295==a)this.h=null,b=!0;else{var d=this.f[a];if(d){b=d.a;if(!b)return;if(c)switch(b){case 3:return;case 2:break;default:d.a=3;window.setTimeout(this.G.bind(null,a,!1,!0),1E3);return}d.a=0;b=!0}}b&&G(this,8,32,[a])};
function W(a,c,b,d){var e=a.f[c],f=256;2==e.a&&(d?(f|=128,e.a=1):f|=64);var g,h,k,m,n;b&&(g=b.left,h=b.top,k=b.right||g+1,m=b.bottom||h+1,n=b.zoom,b=e.port.f)&&(g+=b.left,h+=b.top,k=Math.min(k+b.left,b.right),m=Math.min(m+b.top,b.bottom));G(a,9,f,[c,g,h,k,m,n])}
l.I=function(a){var c=this.b,b=[];if(a)(a=c[a])&&(a.A||a.C||b.push(a.s));else for(var d in c)a=c[d],a.A||a.C||b.push(a.s);if(b.length){c=[15,null,null];a={};var e=this.f;for(d in e){var f=e[d];f.a&&0<=b.indexOf(f.port.tabId)&&(f.b?(f=f.port,f.a||O(this,f,null,a),c[2]=d,f.postMessage(c)):W(this,d,null,!0))}}};function X(a,c,b){if((c=a.b[c])&&!c.C){c=c.s;var d=b?0:2;b=b?32:64;var e=a.f,f;for(f in e){var g=e[f];g.a&&g.port.tabId==c&&g.a!=d&&(g.a=d,G(a,8,b,[f]))}}}
function Y(a,c,b,d){var e=a.ha,f=(e&c)!=((b?63:32)&c);a.ha=b?e|=c:e&=~c;f&&(b=a.c[-1],c=a.c[-2],b=a.H=0!=b&&(e&b)==b,e=a.V=0!=c&&(e&c)==c,a.ja=(b||e)&&d||null)}l.ga=function(a,c,b,d){var e=this.b[a];if(e)if(d)e.C&&window.clearTimeout(e.C),e.C=window.setTimeout(this.ga.bind(null,a,c,b),d);else if(e.C=null,c&&(chrome.windows.get(a,this.J),chrome.tabs.query({windowId:a,active:!0},this.J)),b){if((a=this.b[a])&&!a.C){a=a.s;c=this.f;for(var f in c)b=c[f],b.a&&b.port.tabId==a&&1==b.a&&G(this,8,1152,[f])}}else this.I(a)};
l.J=function(a){a instanceof Array&&(a=a.shift());if(a&&(!a.url||!a.url.startsWith("chrome:")&&!a.url.startsWith("ms-browser-extension:"))){var c=a.windowId||a.id,b=this.b[c];if(b){if(a.windowId)b.s=a.id,a.width&&(b.P=a.width),a.height&&(b.O=a.height);else{var d="fullscreen"==a.state,e=d!=b.A;b.width=a.width;b.height=a.height;b.left=a.left;b.top=a.top;b.Ha="maximized"==a.state;b.A="fullscreen"==a.state;e&&(d?X(this,c):this.I(c))}b.P&&b.O&&(a=b.scale,d=(b.width-b.P)/2,e=b.height-b.O-d,b.border=Math.round(d*
a),150>=e&&(b.fa=Math.round(e*a)));(b=this.b[c])&&b.L&&(a=b.border,d=b.scale,G(this,7,0,[c,a,b.fa,Math.round(b.width*d)-a,Math.round(b.height*d)-a]))}}};function O(a,c,b,d){a=a.a;b=[16,b];for(var e=[c],f;f=a[c.c];c=f){if(d)if(d[c.id])break;else d[c.id]=!0;e.push(f)}for(f=e.pop();c=e.pop();f=c)d=c.Ga,b[2]=d,b[3]=c.frameId,b[4]=d?null:c.url,b[5]=d?null:c.D,f.postMessage(b)}function P(a,c,b){a=a.a;c=[c,null].toString();var d=0,e;for(e in a)e.startsWith(c)&&(a[e].postMessage(b),d++);return d}
l.M=function(a){var c={file:"content.js",runAt:"document_start",allFrames:!0};620756992<this.U&&(c.matchAboutBlank=!0);if(a instanceof Array)for(;a.length;)try{chrome.tabs.executeScript(a.shift().id,c)}catch(b){}else try{chrome.tabs.executeScript(a.id||a,c)}catch(b){}};function Ea(a,c){"object"!=typeof c&&(c=a.b[c]);c&&null==c.L&&G(a,6,17,[c.id,0,c.width,c.height,c.left,c.top,c.scale])}l.qa=function(a){for(;a.length;)this.ta(a.shift(),!0)};l.Fa=function(a){this.ea(a.linkUrl,a.pageUrl,4)};
l.oa=function(a,c){N(this,c.id,a.menuItemId==this.la)};l.La=function(a){var c=a.sender.tab;if(c&&!(0>c.id)){var b=a.id;null==b&&(b=a.id=a.v||this.Da++);var d=c.id,e="top"==a.name;a.tabId=d;a.windowId=0>c.index?null:c.windowId;a.g=!0;a.h=!1;a.a=e;a.frameId=e?0:a.sender.frameId;a.l=0;a.url=a.sender.url||e&&c.url||null;a.D=null;this.o[b]=a;e&&(this.a[d]=a);a.onMessage.addListener(this.Ma.bind(this,a));a.onDisconnect.addListener(this.aa);this.$(a)}};
l.aa=function(a,c){if(a.g){c||(a.g=!1);var b=this.f,d=this.g,e=this.i,f,g,h;for(h in b)if(f=b[h],f.port===a)f.a&&this.G(h),delete b[h];for(h in d)(g=d[h],g.port!==a||g.l)||(delete d[h],r&&delete d[g.id]);for(h in e)e[h].port===a&&delete e[h];this.ja===a&&Y(this,63,!1);if(!c){b=a.tabId;d=a.frameId;e=[b,d].toString();f=this.l;for(h in f)e==f[h].b&&delete f[h];a.a&&delete this.a[b];delete this.a[[b,d]];delete this.o[a.id]}}};
l.Ma=function(a,c){switch(c[0]){case 21:var b=c[1];b&&(a.url=b,null==a.frameId&&this.$(a));break;case 22:var d=this.a,e=d[[a.tabId,c[2]]],b=c[4];e.Ga=c[3];e.f=b;if(d=d[e.c])if(d=d.f)b.left+=d.left,b.top+=d.top,b.right=Math.min(b.right+d.left,d.right),b.bottom=Math.min(b.bottom+d.top,d.bottom);break;case 23:var b=a.windowId,f=a.tabId,g=c[1],d=c[2],e=c[4],h=this.b[b];if(g){if(g=F(this,g)){var h=f==h.s&&!h.A,k=!d||!e;k&&(d=f);if(f=c[7])g.a&&g.F&&g.a!=g.F||(g.a=f),g.F=f;var m=xa(this,d,a,k?null:c[5],
k?null:c[6]),n=h&&!m.a;m.a=h?1:2;g instanceof B&&Z(this,g,2,(h?128:64)|(k?512:0),b,d,f);k||(W(this,d,e),n&&window.setTimeout(this.I.bind(null,b),3E3))}}else c[3]?(this.G(d,!0),delete this.f[d]):e&&f==h.s&&!h.A&&W(this,d,e,!0);break;case 24:b=c[2];(d=this.i[c[1]])&&b&&(d.a&&d.F&&d.a!=d.F||(d.a=b),d.F=b);break;case 25:xa(this,c[1],a,c[2],c[3]);break;case 26:N(this,a.tabId,!0,!0,a,c[1],c[2],c[3]);break;case 27:if(b=this.i[c[1]]){d=b.o;if(e=c[4])if("string"==typeof e&&(e=JSON.parse(e)),e instanceof Array){if(g=
c[5])for(h=0;h<e.length;h++)e[h][3]=g;Array.prototype.push.apply(d,e)}c[3]&&(b.c+=c[3]);c[6]&&(b.pageUrl=c[6]);c[7]&&(b.F=c[7]);++b.w<b.g||(F(this,b.b),b.B?(d=this.b[b.port.windowId])&&d.s==b.tabId&&b.c&&(b.frame=b.v.f,e=b.zoom,G(this,10,0,[4294967295,d.id,Math.round(b.h*e)+d.border,Math.round(b.i*e)+d.fa,0,b.c]),this.h=b.tabId,P(this,b.tabId,[13,!0])):d.length?this.xa(d,b.l,b.H):window.alert(chrome.i18n.getMessage("cannot_find_links")))}break;case 28:this.G(4294967295);break;case 29:Fa(this,a.windowId,
a.tabId);break;case 30:Fa(this,a.windowId,a.tabId,c[1],c[2]);break;case 31:(b=sa[c[1]])&&Y(this,b,c[2],a);break;case 32:0==c[1]&&Y(this,32,c[2],a);break;case 33:Y(this,63,!1);break;case 34:if(b=c[2],d=c[3],e=a.o||a.i)e=[e,b],g={},h=32,g[110]=c[1],g[115]=d,-2==b&&(h|=16),G(this,16,h,e,g)}};
l.Ka=function(a){var c=a.f,b=a.h,d=a.a,e;if(1==c){var f=d[0];if(e=this.w[f])c=e.f,delete this.w[f]}switch(c){case 3:this.S=-1;this.W=a[13]||"m"+d[2];if(b=d[4]){b/=96;a=this.U;this.T=620756992>a?1:620756992<a&&621284967>a?b:637534208<a&&638078312>a?b:1.25<b?b:1;b=this.b;a=this.T;for(var g in b)d=b[g],d=[g,d.L,d.width,d.height,d.left,d.top,d.scale=a],G(this,6,17,d)}this.X&&this.Y();break;case 4:g=this.c;g[-9]=0<(b&64);g[-8]=0<(b&32);g[-4]=0<(b&2);g[-1]=d[0];g[-2]=d[1];g[12]=a[12];M(this,a,1);M(this,
a,2);M(this,a,3);M(this,a,4);M(this,a,10);M(this,a,9,!0);M(this,a,11,!0);if(g=a[13])this.W=g;if(!this.ia){this.ia=!0;this.m(1,chrome.runtime.onConnect,this.La);this.m(1,chrome.webNavigation.onCommitted,this.ra);this.m(1,chrome.webNavigation.onHistoryStateUpdated,this.Ja);this.Wa?(this.m(2,chrome.webRequest.onBeforeRequest,this.N,{urls:["http://*/*","https://*/*"],types:["main_frame","sub_frame"]},["blocking","requestBody"]),this.m(2,chrome.webRequest.onBeforeSendHeaders,this.ca,{urls:["http://*/*",
"https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","requestHeaders"]),this.m(2,chrome.webRequest.onHeadersReceived,this.da,{urls:["http://*/*","https://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["blocking","responseHeaders"])):(this.m(2,chrome.webRequest.onBeforeRequest,this.N,{urls:["http://*/*"],types:["main_frame","sub_frame"]},["blocking"]),this.m(2,chrome.webRequest.onBeforeRequest,this.N,{urls:["https://*/*"],
types:["main_frame","sub_frame"]},["blocking","requestBody"]),this.m(2,chrome.webRequest.onBeforeSendHeaders,this.ca,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["requestHeaders"]),this.m(2,chrome.webRequest.onBeforeSendHeaders,this.ca,{urls:["https://*/*"]},["blocking","requestHeaders"]),this.m(2,chrome.webRequest.onHeadersReceived,this.da,{urls:["http://*/*"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")},["responseHeaders"]),
this.m(2,chrome.webRequest.onHeadersReceived,this.da,{urls:["https://*/*"]},["blocking","responseHeaders"]));this.m(3,chrome.webRequest.onResponseStarted,this.Ua,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});this.m(3,chrome.webRequest.onCompleted,this.Sa,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});this.m(3,chrome.webRequest.onErrorOccurred,this.Ta,{urls:["<all_urls>"],types:"object image main_frame sub_frame xmlhttprequest other".split(" ")});
for(g=0;g<this.v.length;g++)chrome.contextMenus.update(this.v[g],{enabled:!0});chrome.tabs.query({url:x[0]},this.M);chrome.tabs.query({url:x[1]},this.M)}break;case 5:g=d[0];(a=this.b[g])?(b=0!=(b&128),a.A!=b&&(a.A=b)&&X(this,g)):this.ua(g);break;case 6:g=e.a[0];b=d[1];if(g=this.b[g])g.L=b;break;case 8:g=d[0];b&=32;if(4294967295==g)P(this,this.h,[13,!1]),this.h=null;else if(g=this.f[g])g.a=b?0:2;break;case 11:g=d[0];4294967295==g&&(N(this,this.h,!0,!0),this.h=null);break;case 12:try{var h=a.a[5],k=
a[4];g=4==h?2:3;if((1==h||2==h)&&za(this,a)){if(this.c[3].test(k))1==h?g=4:h=4;else if(this.c[-4]||this.c[4].test(k))g=4;a[8]|=256}if(4==h){switch(a.a[4]){case 1:a[7]||(a[7]=a[50]);break;case 3:a[7]||(a[7]=a[32]),a[50]||(a[50]=a[31])}this.wa(a)}else Z(this,a,g)}catch(m){Z(this,a,0)}break;case 1:break;default:!e&&b&1&&G(this,1,0,[a.g,0,0,0])}};
l.wa=function(a,c,b){try{if(null==a.j)if(!c){var d=new I(this,a,!0);this.pa(a,null,d)||chrome.windows.getLastFocused(J(d,2));if(d.c())return}else if(b){var e=this.b[b.id],f=this.a[e&&e.s];f&&(a.j=f.id)}f=this.o[a.j];if(!f)return Z(this,a,0);var g;var h=a.b;h||(h=z.prototype.f++,a.b=h,this.i[h]=a);g=h;if(!f.a){var k=this.a[f.tabId];k&&k.postMessage([14,g])}var m=[15,g,null,a[6],a[17],a[50],a[31]];f.a||O(this,f,g);f.postMessage(m)}catch(n){Z(this,a,0)}};
function Z(a,c,b,d,e,f,g){-1!=b&&(e=[c.g,b,e,f],f={},f[8]=c[8],g&&(f[110]=g),G(a,1,d|(0==b?4:2),e,f))}l.ra=function(a,c){var b=this.a[[a.tabId,a.frameId]];if(b)if(c){var d=a.url;d!=b.url&&(b.url=d,b.l++,y.test(d)&&(b.b=!0),this.aa(b,!0),b.postMessage([17,!1,b.b]))}else this.aa(b)};l.Ja=function(a){return this.ra(a,!0)};
l.ta=function(a,c){var b=a.id,d={id:b,width:a.width,height:a.height,left:a.left,top:a.top,scale:this.T,border:8,fa:73,Ha:"maximized"==a.state,A:"fullscreen"==a.state,O:0,P:0,s:0,L:null,C:null};this.b[b]=d;chrome.tabs.query({windowId:b,active:!0},this.J);chrome.tabs.query({windowId:b,url:x[0]},this.M);chrome.tabs.query({windowId:b,url:x[1]},this.M);c&&Ea(this,d)};l.ua=function(a){G(this,5,32,[a]);delete this.b[a]};l.Va=function(a){if(0<a){var c=this.b[a];c&&(Ea(this,c),r&&this.ga(a,!1,!0,500))}};
l.Ra=function(a,c,b){var d=b.windowId,e=this.b[d];e&&!e.s&&this.J(b);"complete"==c.status&&(a=this.a[a])&&!a.h&&(a.h=!0,this.I(d))};l.Pa=function(a){this.ha=0;this.h&&this.G(4294967295);var c=a.windowId;a=a.tabId;var b=this.a[a];b&&!b.windowId&&(b.windowId=c);if(b=this.b[c])X(this,c),b.s=a,chrome.tabs.get(a,this.J),this.I(c)};l.Qa=function(a,c){var b=c.Ya,d=this.o,e;for(e in d)(port=d[e])&&port.tabId==a&&(port.windowId=b);X(this,b,!0)};
function Fa(a,c,b,d,e){a.h&&a.G(4294967295);var f=a.b[c];f&&f.s==b&&(d&&(f.P=d),e&&(f.O=e),X(a,c),a.ga(c,d||e,!1,250))}
l.N=function(a){var c=a.tabId,b=a.frameId;if(!(0>c||0>b)){var d=a.requestId,e=a.url,f=K(e);if(ja.test(e))return a=this.a[c],this.ea("idmreg"+e.substr(e.indexOf(":")),a&&a.url),{redirectUrl:chrome.extension.getURL("captured.html")};var g;g=[c,b].toString();var h=this.l;g=g in h?h[g]:h[g]=new va(c,b,a.parentFrameId);g.a!=d&&(g.a=d,g.D=e,g.url=null,g.c=!1);if(f&128){e=this.H;g=this.V;if(e&&(a.a=f,a.port=this.a[[c,b]],a.b=0<=w.indexOf(a.type),a.c=e,a.g=g,3==Aa(this,a)))return{redirectUrl:chrome.extension.getURL("captured.html")};
if(!g&&"POST"==a.method&&a.requestBody){c=a.requestBody;if(b=c.raw)for(f=0;f<b.length&&(b[f].bytes||(b=null));f++);if(b||c.formData)(d=this.g[d])?d.requestBody=c:ya(this,a)}}}};
l.ca=function(a){var c=a.tabId;if(0<c){var b=a.type;if("stylesheet"==b||"script"==b)return V(this,d);r&&b.endsWith("_frame")&&this.N(a);var d=a.requestId,e=a.url,f=a.method,g=K(e);if(!g||"GET"!=f&&"POST"!=f)return V(this,d);a.c=this.H;a.g=this.V;var h=this.g[d];h&&(a.id=h.id,a.port=h.port,a.f=h.requestBody,h.a&&(a.D=h.D||h.url,a.w=h.w||h.requestHeaders,a.h=h.h||h.f,a.c=h.c,a.g=h.g));var h=a.c,k=a.v=b.endsWith("_frame");if(!a.port&&!(a.port=this.a[[c,a.frameId]])&&!k||"POST"==f&&g&128&&!a.f||!h&&k&&
!e.includes("?")&&(c=ha.exec(e),(c=Ba(c?c[1]:"").toUpperCase())&&this.c[2].test(c)))return V(this,d);e.includes("#")&&(a.url=Ca(e));a.a=g;a.b=0<=w.indexOf(b);a.l=y.test(e);ya(this,a)}};
l.da=function(a){var c=a.requestId,b=this.g[c];if(b){var d=a.responseHeaders;if("image"==b.type){var e=R(d,"Content-Type");if(e&&e.toLowerCase().startsWith("image/"))return V(this,c)}"quic"==R(d,"Client-Protocol")?b.a|=64:(e=R(d,"Alternate-Protocol"))&&e.endsWith(":quic,p=0")&&"chunked"!=R(d,"Transfer-Encoding")&&(b.a|=64);if(b.a&192){var e=a.statusLine,f=parseInt(e.split(" ",2).pop());b.statusLine=e;b.statusCode=f;b.B=0<=ga.indexOf(f);b.responseHeaders=d;if(3==Aa(this,b))return r?(V(this,c,a,b.b),
{redirectUrl:chrome.extension.getURL("captured.html")}):{responseHeaders:[{name:"Connection",value:"close"},{name:"Content-Type",value:"multipart/related"},{name:"Content-Length",value:"0"}]}}}};l.Ua=function(a){var c=a.requestId,b=this.g[c];if(b){if(b.v){var d=this.l[[b.tabId,b.frameId]];d&&(d.url=b.url)}V(this,c,a,b.b)}};l.Sa=function(a){V(this,a.requestId,a)};l.Ta=function(a){V(this,a.requestId)};
l.Y=function(a,c,b,d,e){if(void 0===a&&(this.X=!1,a=new I(this,!0),chrome.storage.local.get("version",J(a,1)),r||(chrome.extension.isAllowedIncognitoAccess(J(a,2)),chrome.management.get(ca,J(a,3)),chrome.management.get(da,J(a,4))),a.c()))return;a=chrome.runtime.getManifest();a=a.version||"";"object"==typeof c&&(c=c.version||"");r||("object"==typeof d&&(d=d.enabled&&d.id),d&&chrome.management.setEnabled(d,!1),"object"==typeof e&&(e=e.enabled&&e.id),e&&chrome.management.setEnabled(e,!1),b=null!=b&&
!b);if(a&&a!=c&&null!=c){chrome.storage.local.set({version:a});d=this.W;var f=r&&d<ba;if(!c||!d||f||e)a="current="+a,c&&(a+="&previous="+c),b&&(a+="&incognito=1"),e&&(a+="&mulsrch=1"),d&&(a+="&manager="+d),f&&(a+="&update=1"),r&&(a+="&msedge=1"),chrome.tabs.create({url:chrome.extension.getURL("welcome.html?"+a)})}};l.m=function(a,c){var b=Array.prototype.slice.call(arguments);this.ka.push(b);c.addListener.apply(c,b.slice(2))};
function I(a){this.caller=arguments.callee.caller;this.f=a;this.b=Array.prototype.slice.call(arguments,1);this.a=0}function J(a,c){a.a++;return a.h.bind(a,c)}I.prototype.c=function(){return this.a?(arguments.length&&(this.b=Array.prototype.slice.call(arguments)),!0):!1};I.prototype.h=function(a,c){this.b[a]=c;0==--this.a&&this.caller.apply(this.f,this.b)};
I.prototype.g=function(a,c,b){var d=Array.prototype.slice.call(arguments,3);b&&(d=b.concat(d));a.apply(c,d);this&&0==--this.a&&this.caller.apply(this.f,this.b)};function H(a){var c=Array.prototype.slice.call(arguments,1),b=c[c.length-1];b instanceof I?b.a++:b=null;return I.prototype.g.bind(b,arguments.callee.caller,a,c)}function Ca(a){var c=a.lastIndexOf("#");return 0>c||c<a.indexOf("?")?a:a.substr(0,c)}
function L(a){for(var c="",b=0;b<a.length;b++)c&&(c+="; "),c+=a[b].name,c+="=",c+=a[b].value;return c}function U(a){if(!a||!a.length)return null;for(var c="",b=0;b<a.length;b++)c+=a[b].name,c+=": ",c+=a[b].value,c+="\n";return c}function R(a,c){if(!a)return null;c=c.toLowerCase();for(var b=0;b<a.length;b++)if(a[b].name.toLowerCase()==c)return a[b].value;return null}
function T(a,c){if(!a)return null;c=c.toLowerCase();var b=a.split(";");b.shift();for(var d=0;d<b.length;d++){var e=b[d],f=e.indexOf("=");if(0<f){var g=e.substr(0,f).trim().toLowerCase(),h="*"==g[g.length-1];h&&(g=g.substr(0,g.length-1).trimRight());if(g==c)return b=e.substr(f+1).trim(),d=b.length-1,'"'==b[0]&&'"'==b[d]&&(b=b.substring(1,d)),h&&(b=b.split("'",3).pop()),unescape(b)}else if(0>f&&e.trim().toLowerCase()==c)return""}return null}
function S(a){return a&&unescape(a.split(";",1).shift().trim())||""}
function Da(a,c){if(!a)return null;var b=a.raw;if(b){for(var d=String.fromCharCode,e="",f=0;f<b.length;f++){var g=b[f].bytes;if(!g)return null;for(var g=new Uint8Array(g),h=g.length,k=0;k<h;k++)e+=d(g[k])}return e}b=a.formData;if(!b)return null;f=S(c).toLowerCase();e=[];if("application/x-www-form-urlencoded"==f)for(d in b)for(g=b[d],d=d.split(" ").map(encodeURIComponent).join("+"),f=0;f<g.length;f++)e.length&&e.push("&"),e.push(d,"=",g[f].split(" ").map(encodeURIComponent).join("+"));else if("multipart/form-data"==
f){(h=T(c,"boundary"))||(h="----WebKitFormBoundary"+Math.random().toString(36).substr(2));for(d in b)for(g=b[d],f=0;f<g.length;f++)e.push("--",h,'\r\nContent-Disposition: form-data; name="',d,'"\r\n\r\n',g[f],"\r\n");e.push("--",h,"--\r\n")}else return null;return e.join("")}function Ba(a){return(a=ia.exec(a))?a[1]:""}function K(a,c){var b=a.split("://",1).shift().toLowerCase(),b=ta[b]||0;return c?b&31:b}String.prototype.startsWith||(String.prototype.startsWith=function(a){return 0==this.indexOf(a)});
String.prototype.endsWith||(String.prototype.endsWith=function(a){var c=this.length-a.length;return 0<=c&&this.indexOf(a,c)==c});String.prototype.includes||(String.prototype.includes=function(a){return 0<=this.indexOf(a)});new E;
